# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ZerOne
email: duds.dev@gmail.com
description: "Meu blog pessoal"
baseurl: "/zerone"
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dudsDev
github_username:  duFarsoft

# Build settings
markdown: kramdown
# permalink: /:categories/:year/:mounth/:day/:title
# permalink: /:year/:month/:day/:title
# permalink: /palavra/:title

permalink: /:title